#! /bin/sh
# 
# Laptop mode tools module: Ethernet power saving tweaks.
#

if [ x$CONTROL_ETHERNET = x1 ] ; then
	if [ $ON_AC -eq 1 ]; then
		for DEVICE in $ETHERNET_DEVICES ; do
			speed=`mii-tool -v $DEVICE | grep capabilities | tr ' ' '\n' | sort -n | sed -ne '/^1.*/p' | cut -d "b" -f1`
			max_s=0;
			min_s=100000;
			for s in speed;
			do
				if [ $s -gt $max_s ]; then
					max_s=$s
				fi
				if [ $s -lt $min_s ]; then
					min_s=$s
				fi
			done

			case "$MAX_SPEED" in
				"slowest")
				MAX_SPEED=$min_s
				;;
				"fastest")
				MAX_SPEED=$max_s
				;;
			esac
			
			case "$MIN_SPEED" in
				"slowest")
				MIN_SPEED=$min_s
				;;
				"fastest")
				MIN_SPEED=$max_s
				;;
			esac

			# Wakeup-on-LAN handling
			if [ x$DISABLE_WAKEUP_ON_LAN = x1 ] ; then
				if ethtool -s $DEVICE wol p >> $OUTPUT 2>&1 ; then			
					$LM_VERBOSE && echo "Enabled wakeup-on-LAN for $DEVICE" >> $OUTPUT
				else
					$LM_VERBOSE && echo "Could not enable wakeup-on-LAN for $DEVICE" >> $OUTPUT
				fi
			fi
		
			# Handle auto-negotiation
			if  ethtool -s $DEVICE autoneg on >> $OUTPUT 2>&1 ; then
				$LM_VERBOSE && echo "Switched auto-negotiation to on for $DEVICE" >> $OUTPUT
			else
				$LM_VERBOSE && echo "Could not set auto-negotiation to on for $DEVICE" >> $OUTPUT
			fi

			# Handle Speed Throttling
			if  ethtool -s $DEVICE speed $MAX_SPEED  >> $OUTPUT 2>&1 ; then
				$LM_VERBOSE && echo "Restored speed to $MAX_SPEED Mbit for $DEVICE" >> $OUTPUT
			else
				$LM_VERBOSE && echo "Could not restore speed for $DEVICE" >> $OUTPUT
			fi
		done
	else
		for DEVICE in $ETHERNET_DEVICES ; do
			speed=`mii-tool -v $DEVICE | grep capabilities`
			speed=(${speed//base/ });

			case "$MAX_SPEED" in
				"slowest")
				MAX_SPEED=${speed[${#speed[@]} - 2 ]}
				;;
				"fastest")
				MAX_SPEED=${speed[1]}
				;;
			esac
			
			case "$MIN_SPEED" in
				"slowest")
				MIN_SPEED=${speed[${#speed[@]} - 2 ]}
				;;
				"fastest")
				MIN_SPEED=${speed[1]}
				;;
			esac

			# Wakeup-on-LAN handling
			if [ x$DISABLE_WAKEUP_ON_LAN = x1 ] ; then
				if ethtool -s $DEVICE wol d >> $OUTPUT 2>&1 ; then			
					$LM_VERBOSE && echo "Disabled wakeup-on-LAN for $DEVICE" >> $OUTPUT
				else
					$LM_VERBOSE && echo "Could not disable wakeup-on-LAN for $DEVICE" >> $OUTPUT
				fi
			fi
			
			# Handle throttling
			THROTTLE_ETHERNET="$BATT_THROTTLE_ETHERNET"
			if [ x$THROTTLE_ETHERNET = x1 ] ; then
				if  ethtool -s $DEVICE autoneg off speed $MIN_SPEED  >> $OUTPUT 2>&1 ; then
					$LM_VERBOSE && echo "Throttled speed to $MIN_SPEED Mbit for $DEVICE" >> $OUTPUT
				else
					$LM_VERBOSE && echo "Could not throttle $DEVICE" >> $OUTPUT
				fi
			fi
		done
	fi
else
	$LM_VERBOSE && echo "Ethernet module is disabled." >> $OUTPUT
fi
