#! /bin/sh
# 
# Laptop mode tools module: Intel HDA integrated audio power saving mode.
#

if [ x$CONTROL_INTEL_HDA_POWER = x1 ] ; then
        if [ -w /sys/module/snd_hda_intel/parameters/power_save ]; then
                echo 1 > /sys/module/snd_hda_intel/parameters/power_save
                $LM_VERBOSE && echo "Intel HDA power save mode enabled." >> $OUTPUT
        else
                $LM_VERBOSE && echo "Intel HDA power saving is not available on this system." >> $OUTPUT
        fi
else
	$LM_VERBOSE && echo "Intel HDA audio power setting is disabled." >> $OUTPUT
fi
