#! /bin/sh
#
# Laptop mode tools module: control LCD brightness
#



# Control LCD brightness
if [ x$CONTROL_BRIGHTNESS = x1 ] ; then
	if [ $ON_AC -eq 1 ]; then
		if [ "$ACTIVATE" -eq 1 ]; then
			BRIGHTNESS_COMMAND="$LM_AC_BRIGHTNESS_COMMAND"
		else
			BRIGHTNESS_COMMAND="$NOLM_AC_BRIGHTNESS_COMMAND"
		fi
	else
		BRIGHTNESS_COMMAND="$BATT_BRIGHTNESS_COMMAND"
	fi
	if [ -f /var/run/laptop-mode-tools/state-brightness-command ] ; then
		OLD_BRIGHTNESS_COMMAND="$( cat /var/run/laptop-mode-tools/state-brightness-command )"
	fi
	
	if [ "$FORCE" -ne 0 -o "$BRIGHTNESS_COMMAND" != "$OLD_BRIGHTNESS_COMMAND" ] ; then
		$LM_VERBOSE && echo "Set LCD brightness using command $BRIGHTNESS_COMMAND \> $BRIGHTNESS_OUTPUT." >> $OUTPUT
		if ( $BRIGHTNESS_COMMAND > $BRIGHTNESS_OUTPUT ) ; then
			$LM_VERBOSE && echo "Command succeeded." >> $OUTPUT
		else
			echo "The configured LCD brightness command of the lcd-brightness module failed." >> /dev/stderr
			echo "Please check your configuration in /etc/laptop-mode/conf.d/lcd-brightness.conf." >> /dev/stderr
			$LM_VERBOSE && echo "Command failed."  >> $OUTPUT
		fi
		echo -n $BRIGHTNESS_COMMAND > /var/run/laptop-mode-tools/state-brightness-command
	else
		$LM_VERBOSE && echo "Not setting LCD brightness -- command was the same as last time." >> $OUTPUT
	fi
fi

