#! /bin/sh
#
# Laptop mode tools module: virtual terminal blanking
#



# Set terminal blanking/powerdown timeouts
if [ x$CONTROL_TERMINAL = x1 ] ; then
	if [ $ON_AC -eq 1 ]; then
		if [ "$ACTIVATE" -eq 1 ]; then
			BLANK_MINUTES="$LM_AC_TERMINAL_BLANK_MINUTES"
			POWERDOWN_MINUTES="$LM_AC_TERMINAL_POWERDOWN_MINUTES"
		else
			BLANK_MINUTES="$NOLM_AC_TERMINAL_BLANK_MINUTES"
			POWERDOWN_MINUTES="$NOLM_AC_TERMINAL_POWERDOWN_MINUTES"
		fi
	else
		BLANK_MINUTES="$BATT_TERMINAL_BLANK_MINUTES"
		POWERDOWN_MINUTES="$BATT_TERMINAL_POWERDOWN_MINUTES"
	fi
	echo "Set terminal blanking timeout to $BLANK_MINUTES min, powerdown timeout to $POWERDOWN_MINUTES min." >> $OUTPUT
	for THISTERMINAL in $TERMINALS ; do
		if [ -e $THISTERMINAL ] ; then
			echo "Terminal $THISTERMINAL found, adjusting." >> $OUTPUT
			TERM=linux setterm -blank "$BLANK_MINUTES" -powerdown "$POWERDOWN_MINUTES" > $THISTERMINAL
		else
			echo "Terminal $THISTERMINAL does not exist." >> $OUTPUT
		fi
	done
else
	echo "CONTROL_TERMINAL is disabled, skipping..." >> $OUTPUT
fi

