#! /bin/sh
# 
# Laptop mode tools module, called from /usr/sbin/laptop_mode.
# Configuration in /etc/laptop-mode/conf.d/wireless-power.conf.
#
# PURPOSE: power saving for generic wireless adapters that support
#          the iwconfig power command.
#

#
# Find all the wireless devices.
# Place the interface names on the list WIFI_IFNAMES.
#
findWifiIfs () {
	local DEVICE;
	
	for DEVICE in /sys/class/net/*; do
		dev=`basename $DEVICE`
                # Check if it is a wireless device
                $IWCONFIG $dev >/dev/null 2>&1;
                ret=$?;
                if [ "$ret" = "0" ]; then
		        # Add the interface name to the list
	    		WIFI_IFNAMES="$WIFI_IFNAMES ${DEVICE##*/}"
                fi
	done
}

if [ x$CONTROL_WIRELESS_POWER_SAVING = x1 ] || [ x$ENABLE_AUTO_MODULES = x1 -a x$CONTROL_WIRELESS_POWER_SAVING = xauto ]; then
	log "VERBOSE" "Setting power saving for generic wireless interfaces."

	# Provide defaults for config file settings
	[ "$WIRELESS_AC_POWER_SAVING" ]   || WIRELESS_AC_POWER_SAVING=0
	[ "$WIRELESS_BATT_POWER_SAVING" ] || WIRELESS_BATT_POWER_SAVING=1

	# Find executables
	if [ -x /sbin/iwconfig ] ; then
		IWCONFIG=/sbin/iwconfig
	elif [ -x /usr/sbin/iwconfig ] ; then
		IWCONFIG=/usr/sbin/iwconfig
	else
		log "VERBOSE" "iwconfig is not installed"
	fi

	# Translate 1 => on, 0 => off
	WIRELESS_AC_POWER_SAVING_ONOFF=off
	WIRELESS_BATT_POWER_SAVING_ONOFF=off
	[ "$WIRELESS_AC_POWER_SAVING" = 1 ] && WIRELESS_AC_POWER_SAVING_ONOFF=on
	[ "$WIRELESS_BATT_POWER_SAVING" = 1 ] && WIRELESS_BATT_POWER_SAVING_ONOFF=on

	WIFI_IFNAMES=""
	findWifiIfs
	for IF in $WIFI_IFNAMES ; do
		if [ $ON_AC -eq 1 ] ; then
			log "VERBOSE" "On AC power: setting power saving mode for $IF to $WIRELESS_AC_POWER_SAVING_ONOFF."
			if ( ! iwconfig $IF power $WIRELESS_AC_POWER_SAVING_ONOFF ) ; then
				log "ERR" "Failed."
			fi
		else
			log "VERBOSE" "On battery: setting power saving mode for $IF to $WIRELESS_BATT_POWER_SAVING_ONOFF."
			if ( ! iwconfig $IF power $WIRELESS_BATT_POWER_SAVING_ONOFF ) ; then
				log "ERR" "Failed."
			fi
		fi
	done
else
	log "VERBOSE" "Generic wireless interface power saving module is disabled."
fi

