#!/bin/sh
#
# chkconfig: - 20 90
# description: Starts and stops "laptop-mode" - tweaks system behavior
#              to extend battery life.
#
# config:  /etc/laptop-mode/laptop-mode.conf

test -f /usr/sbin/laptop_mode || exit 0

. /lib/lsb/init-functions

# Enable laptop mode when the system is booted when running on battery.

TEMPFILE=`mktemp`
echo "Failed to start laptop mode" > $TEMPFILE


trap "log_failure_msg $( cat $TEMPFILE ) ; rm $TEMPFILE; exit 10" HUP INT ABRT QUIT SEGV TERM
set -e

case $1 in
  start)
    touch /var/run/laptop-mode-enabled
    /usr/sbin/laptop_mode auto > $TEMPFILE
    log_success_msg $( cat $TEMPFILE )
    ;;

  restart|reload|force-reload)
    # Full restart: first stop laptop mode completely (to restore default mount options etc.)
    rm -f /var/run/laptop-mode-enabled
    /usr/sbin/laptop_mode stop > $TEMPFILE
    log_success_msg $( cat $TEMPFILE )
    
    # Now remove files containing stored status, re-enable, and start it up again.
    rm -f /var/run/laptop-mode-*
    touch /var/run/laptop-mode-enabled
    /usr/sbin/laptop_mode auto force > $TEMPFILE
    log_success_msg $( cat $TEMPFILE )
    ;;

  stop)
    rm -f /var/run/laptop-mode-enabled
    /usr/sbin/laptop_mode stop > $TEMPFILE
    log_success_msg $( cat $TEMPFILE )    
    ;;

  status)
    echo "Laptop mode status:"
    echo
    /usr/sbin/laptop_mode status
    ;;
    
  *)
    echo "Usage: $0 {stop|start|restart|reload|force-reload|status}" >&2
    exit 2
    ;;
esac
exit 0
