#! /bin/sh
#
# chkconfig: - 99 99
# description: Starts and stops "laptop-mode" - tweaks system behavior
#              to extend battery life.
#
# config:  /etc/laptop-mode/laptop-mode.conf

### BEGIN INIT INFO
# Provides:          laptop-mode
# Required-Start:    $remote_fs
# Required-Stop:     $remote_fs
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Enable laptop-mode-tools power management functions
# Description:       Enable laptop-mode-tools power management functions
### END INIT INFO

test -f /usr/sbin/laptop_mode || exit 0

if [ -f /lib/lsb/init-functions ] ; then
  . /lib/lsb/init-functions
else
  log_success_msg()
  {
    logger -t LAPTOP-MODE -p daemon.info -- $*
    echo "$*"
  }
  log_failure_msg()
  {
    logger -t LAPTOP-MODE -p daemon.notice -- $*
    echo "$*"
  }
fi

# Enable laptop mode when the system is booted when running on battery.

case $1 in
  start)
    # Clean-up any possibilities of a leftover
    # From the initscript, we want a clean start
    test -f /var/run/laptop-mode-tools/enabled && rm -f /var/run/laptop-mode-tools/enabled
    test -f /var/run/laptop-mode-tools/state && rm -f /var/run/laptop-mode-tools/state

    if RESULT=`/usr/sbin/laptop_mode auto` ; then
      log_success_msg "$RESULT"
    else
      log_failure_msg "$RESULT"
    fi
    ;;

  restart)
      $0 stop;
      $0 start;
    ;;

  reload|force-reload)
    if RESULT=`/usr/sbin/laptop_mode auto` ; then
      log_success_msg "$RESULT"
    else
      log_failure_msg "$RESULT"
    fi
    ;;

  stop)
    if RESULT=`/usr/sbin/laptop_mode stop` ; then
      log_success_msg "$RESULT"
    else
      log_failure_msg "$RESULT"
    fi

    # Clean-up any possibilities of a leftover
    # From the initscript, we want a clean start
    test -f /var/run/laptop-mode-tools/enabled && rm -f /var/run/laptop-mode-tools/enabled
    test -f /var/run/laptop-mode-tools/state && rm -f /var/run/laptop-mode-tools/state
    ;;

  status)
    echo "Laptop mode status:"
    echo
    /usr/sbin/laptop_mode status
    ;;

  *)
    echo "Usage: $0 {stop|start|restart|reload|force-reload|status}" >&2
    exit 2
    ;;
esac

exit 0
